version: "3"
services:
  devdoc-swissknife:
    image: devdoc-swissknife:22.04
    depends_on:
      - kroki
    environment:
      - SERVICE_KROKI=http://kroki:8000
    volumes:
      - ./docs_src:/data/docs_src
      - ./docs_out:/data/docs_out
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
  kroki:
    image: yuzutech/kroki
    depends_on:
      - blockdiag
      - mermaid
      - bpmn
      - excalidraw
    environment:
      - KROKI_BLOCKDIAG_HOST=blockdiag
      - KROKI_MERMAID_HOST=mermaid
      - KROKI_BPMN_HOST=bpmn
      - KROKI_EXCALIDRAW_HOST=excalidraw
    ports:
      - "8000:8000"
  blockdiag:
    image: yuzutech/kroki-blockdiag
    expose:
      - "8001"
  mermaid:
    image: yuzutech/kroki-mermaid
    expose:
      - "8002"
  bpmn:
    image: yuzutech/kroki-bpmn
    expose:
      - "8003"
  excalidraw:
    image: yuzutech/kroki-excalidraw
    expose:
      - "8004"
