# NOTE: it's ugly :( but works. Just don't look at this now

.PHONY: devdoc-swissknife-en
devdoc-swissknife-en:
	cd devdoc-swissknife-en &&\
	bash ../render_doc.sh devdoc-swissknife-en

.PHONY: all
all: devdoc-swissknife-en
